/* eslint-disable  */
import ClientHelmetProvider from "@/providers/ClientHelmetProviders";
import { AuthProvider } from "@/providers/useAuth";
import { Geist, Geist_Mono } from "next/font/google";
import DefaultLayout from "./(common-pages)/default-layout/page";
import "./globals.css";
import QueryProvider from "./QueryProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Starter Kit",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <QueryProvider>
          <ClientHelmetProvider>
            <AuthProvider>
              <DefaultLayout>{children}</DefaultLayout>
            </AuthProvider>
          </ClientHelmetProvider>
          <ToastContainer />
        </QueryProvider>
      </body>
    </html>
  );
}
