export const Tags = [
  {
    _id: {
      $oid: "694d184e679c82ef4023490e",
    },
    title: "Eco-Tourism",
    sort_order: 6,
    is_active: true,
  },
  {
    _id: {
      $oid: "694d184e679c82ef40234911",
    },
    title: "Romantic Getaway",
    sort_order: 9,
    is_active: true,
  },
  {
    _id: {
      $oid: "694d184e679c82ef40234914",
    },
    title: "Staycation",
    sort_order: 12,
    is_active: true,
  },
  {
    _id: {
      $oid: "694d184e679c82ef4023490a",
    },
    title: "Asian Cuisine",
    sort_order: 2,
    is_active: true,
  },
  {
    _id: {
      $oid: "694d184e679c82ef40234909",
    },
    title: "Luxury Stay",
    sort_order: 1,
    is_active: true,
  },
  {
    _id: {
      $oid: "694d184e679c82ef4023490c",
    },
    title: "Family Friendly",
    sort_order: 4,
    is_active: true,
  },
  {
    _id: {
      $oid: "694d184e679c82ef4023490f",
    },
    title: "Wedding Venue",
    sort_order: 7,
    is_active: true,
  },
  {
    _id: {
      $oid: "694d184e679c82ef4023490d",
    },
    title: "Business Travel",
    sort_order: 5,
    is_active: true,
  },
  {
    _id: {
      $oid: "694d184e679c82ef4023490b",
    },
    title: "Wellness & Spa",
    sort_order: 3,
    is_active: true,
  },
  {
    _id: {
      $oid: "694d184e679c82ef40234913",
    },
    title: "Adventure",
    sort_order: 11,
    is_active: true,
  },
  {
    _id: {
      $oid: "694d184e679c82ef40234910",
    },
    title: "Cultural Experience",
    sort_order: 8,
    is_active: true,
  },
  {
    _id: {
      $oid: "694d184e679c82ef40234912",
    },
    title: "Special Offers",
    sort_order: 10,
    is_active: true,
  },
];
export const Testimonial = [
  {
    _id: {
      $oid: "694d338d679c82ef4023491d",
    },
    author_name: "David Miller",
    author_address: "Sydney, Australia",
    desc: "I ordered room service dinner several times during my stay. The Wagyu beef burger was cooked to perfection, and the Indonesian Satay was incredibly flavorful. Even though it was delivered to my room, the food arrived piping hot and beautifully plated. It is rare to find hotel food that maintains such high quality through room service.",
    rating: 4,
    is_active: true,
    is_food: true,
    is_room: false,
    sort_order: 6,
  },
  {
    _id: {
      $oid: "694d338d679c82ef40234918",
    },
    author_name: "Aarav Sharma",
    author_address: "Mumbai, India",
    desc: "The Deluxe Suite exceeded all my expectations. The fusion of modern technology with traditional Asian decor created a serene atmosphere. I particularly loved the panoramic view of the city skyline and the high-quality linens. The room service was prompt, and the nightly turndown service with herbal tea was a thoughtful touch.",
    rating: 5,
    is_active: true,
    is_food: false,
    is_room: true,
    sort_order: 1,
  },
  {
    _id: {
      $oid: "694d338d679c82ef4023491a",
    },
    author_name: "Yuki Tanaka",
    author_address: "Tokyo, Japan",
    desc: "The garden view room was incredibly peaceful. Everything was spotlessly clean, reflecting high standards of hygiene. The soundproofing was excellent, ensuring a deep and uninterrupted sleep despite the hotel being in a central location. It felt like a private sanctuary in the middle of a bustling metropolis. I will definitely return next year.",
    rating: 4,
    is_active: true,
    is_food: false,
    is_room: true,
    sort_order: 3,
  },
  {
    _id: {
      $oid: "694d338d679c82ef4023491b",
    },
    author_name: "Jeremy Clements",
    author_address: "London, UK",
    desc: "The breakfast buffet at the hotel restaurant is a culinary journey across Asia. I especially enjoyed the authentic Laksa and the freshly made Dim Sum. The ingredients were clearly fresh, and the presentation was top-notch. The staff were attentive and remembered my coffee preference every single morning. A truly five-star dining experience.",
    rating: 5,
    is_active: true,
    is_food: true,
    is_room: false,
    sort_order: 4,
  },
  {
    _id: {
      $oid: "694d338d679c82ef40234919",
    },
    author_name: "Mei Ling",
    author_address: "Singapore",
    desc: "I stayed in the Executive Room during a business trip. The workspace was ergonomically designed and the high-speed internet was very reliable for my international zoom calls. The bathroom featured a rain shower and premium spa products that helped me relax after a very long day of meetings. Highly recommended for professionals.",
    rating: 5,
    is_active: true,
    is_food: false,
    is_room: true,
    sort_order: 2,
  },
  {
    _id: {
      $oid: "694d338d679c82ef4023491c",
    },
    author_name: "Fatima Al-Sayed",
    author_address: "Dubai, UAE",
    desc: "We dined at the signature Thai restaurant inside the hotel. The green curry had the perfect balance of spice and creaminess, reminiscent of authentic street food but served in a fine-dining setting. The ambiance was sophisticated, and the live traditional music added a wonderful layer to our dinner. The mango sticky rice was the perfect end.",
    rating: 5,
    is_active: true,
    is_food: true,
    is_room: false,
    sort_order: 5,
  },
];
// ─── ROOM SERVICES ───────────────────────────────────────────────────────────
export const roomServicesData = [
  { title: "Free Wi-Fi", is_active: true, sort_order: 1 },
  { title: "24-Hour Room Service", is_active: true, sort_order: 2 },
  { title: "Daily Housekeeping", is_active: true, sort_order: 3 },
  { title: "Laundry & Dry Cleaning", is_active: true, sort_order: 4 },
  { title: "Airport Shuttle", is_active: true, sort_order: 5 },
  { title: "Concierge Service", is_active: true, sort_order: 6 },
  { title: "Breakfast Included", is_active: true, sort_order: 7 },
  { title: "Valet Parking", is_active: false, sort_order: 8 },
  { title: "Spa & Wellness Access", is_active: true, sort_order: 9 },
  { title: "Swimming Pool Access", is_active: true, sort_order: 10 },
  { title: "Gym Access", is_active: true, sort_order: 11 },
  { title: "Baby Cot on Request", is_active: false, sort_order: 12 },
];

// ─── ROOM FEATURES ───────────────────────────────────────────────────────────
export const roomFeaturesData = [
  { title: "King-Size Bed", is_active: true, sort_order: 1 },
  { title: "Air Conditioning", is_active: true, sort_order: 2 },
  { title: "Flat-Screen TV", is_active: true, sort_order: 3 },
  { title: "Mini Bar", is_active: true, sort_order: 4 },
  { title: "Private Balcony", is_active: true, sort_order: 5 },
  { title: "City View", is_active: true, sort_order: 6 },
  { title: "Ocean View", is_active: true, sort_order: 7 },
  { title: "In-Room Safe", is_active: true, sort_order: 8 },
  { title: "Sofa / Sitting Area", is_active: true, sort_order: 9 },
  { title: "Work Desk", is_active: true, sort_order: 10 },
  { title: "Wardrobe / Closet", is_active: true, sort_order: 11 },
  { title: "Blackout Curtains", is_active: false, sort_order: 12 },
];

// ─── BATHROOM FEATURES ───────────────────────────────────────────────────────
export const bathroomFeaturesData = [
  { title: "Rain Shower", is_active: true, sort_order: 1 },
  { title: "Bathtub", is_active: true, sort_order: 2 },
  { title: "Double Vanity", is_active: true, sort_order: 3 },
  { title: "Heated Towel Rail", is_active: true, sort_order: 4 },
  { title: "Complimentary Toiletries", is_active: true, sort_order: 5 },
  { title: "Hair Dryer", is_active: true, sort_order: 6 },
  { title: "Magnifying Mirror", is_active: false, sort_order: 7 },
  { title: "Bidet", is_active: true, sort_order: 8 },
  { title: "Marble Flooring", is_active: true, sort_order: 9 },
  { title: "Jacuzzi", is_active: false, sort_order: 10 },
  { title: "Steam Shower", is_active: false, sort_order: 11 },
  { title: "Underfloor Heating", is_active: true, sort_order: 12 },
];

// ─── ROOMS ───────────────────────────────────────────────────────────────────
// NOTE: room_services / room_features / room_bathroom_features must be replaced
// with real ObjectIds after inserting the sub-documents above.
export const roomsData = [
  {
    title: "Deluxe King Room",
    short_desc: "Spacious deluxe room with king bed and city view.",
    description:
      "Experience ultimate comfort in our Deluxe King Room featuring a plush king-size bed, modern amenities, and panoramic city views. Ideal for business and leisure travelers alike.",
    price: 120,
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
    bed_count: 1,
    max_person: 2,
    floor: 3,
    room_size: 35,
    room_services: [],
    room_features: [],
    room_bathroom_features: [],
    room_rating: "4.8",
    is_active: true,
    sort_order: 1,
    is_booked: false,
    is_deluxe: true,
    is_double: false,
    is_featured: true,
    is_executive: false,
    is_suite: false,
  },
  {
    title: "Superior Double Room",
    short_desc: "Elegant double room perfect for couples.",
    description:
      "Our Superior Double Room offers a welcoming retreat with twin double beds, warm lighting, and garden-facing views. A perfect choice for couples or friends traveling together.",
    price: 95,
    image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800",
    bed_count: 2,
    max_person: 3,
    floor: 2,
    room_size: 30,
    room_services: [],
    room_features: [],
    room_bathroom_features: [],
    room_rating: "4.5",
    is_active: true,
    sort_order: 2,
    is_booked: false,
    is_deluxe: false,
    is_double: true,
    is_featured: false,
    is_executive: false,
    is_suite: false,
  },
  {
    title: "Executive Suite",
    short_desc: "Premium suite with separate living area and ocean view.",
    description:
      "Indulge in our Executive Suite — a sophisticated blend of luxury and functionality. Featuring a separate living room, kitchenette, king bed, and sweeping ocean vistas.",
    price: 280,
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800",
    bed_count: 1,
    max_person: 2,
    floor: 8,
    room_size: 75,
    room_services: [],
    room_features: [],
    room_bathroom_features: [],
    room_rating: "4.9",
    is_active: true,
    sort_order: 3,
    is_booked: false,
    is_deluxe: false,
    is_double: false,
    is_featured: true,
    is_executive: true,
    is_suite: false,
  },
  {
    title: "Presidential Suite",
    short_desc: "The pinnacle of luxury — our flagship suite.",
    description:
      "The Presidential Suite redefines opulence. Spanning two floors, it features a private dining room, butler service, a grand piano, and floor-to-ceiling panoramic windows.",
    price: 650,
    image: "https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800",
    bed_count: 2,
    max_person: 4,
    floor: 12,
    room_size: 180,
    room_services: [],
    room_features: [],
    room_bathroom_features: [],
    room_rating: "5.0",
    is_active: true,
    sort_order: 4,
    is_booked: false,
    is_deluxe: false,
    is_double: false,
    is_featured: true,
    is_executive: false,
    is_suite: true,
  },
  {
    title: "Standard Single Room",
    short_desc: "Cozy and affordable room for solo travelers.",
    description:
      "A smart, well-appointed room designed for the solo traveler. Features a comfortable single bed, work desk, and all essential amenities at an unbeatable value.",
    price: 60,
    image: "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=800",
    bed_count: 1,
    max_person: 1,
    floor: 1,
    room_size: 20,
    room_services: [],
    room_features: [],
    room_bathroom_features: [],
    room_rating: "4.2",
    is_active: true,
    sort_order: 5,
    is_booked: false,
    is_deluxe: false,
    is_double: false,
    is_featured: false,
    is_executive: false,
    is_suite: false,
  },
  {
    title: "Family Room",
    short_desc: "Generous room designed for families with children.",
    description:
      "Our spacious Family Room accommodates up to 5 guests with two queen beds and a sofa bed. Comes with a dedicated kids' corner and child-safe amenities.",
    price: 175,
    image: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800",
    bed_count: 3,
    max_person: 5,
    floor: 2,
    room_size: 55,
    room_services: [],
    room_features: [],
    room_bathroom_features: [],
    room_rating: "4.6",
    is_active: true,
    sort_order: 6,
    is_booked: false,
    is_deluxe: false,
    is_double: true,
    is_featured: false,
    is_executive: false,
    is_suite: false,
  },
  {
    title: "Honeymoon Suite",
    short_desc: "Romantic suite with jacuzzi and rose petal turndown.",
    description:
      "Crafted for romance, our Honeymoon Suite features a private jacuzzi, canopy king bed, champagne welcome, and breathtaking sunset views over the coastline.",
    price: 350,
    image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?w=800",
    bed_count: 1,
    max_person: 2,
    floor: 9,
    room_size: 80,
    room_services: [],
    room_features: [],
    room_bathroom_features: [],
    room_rating: "4.9",
    is_active: true,
    sort_order: 7,
    is_booked: false,
    is_deluxe: true,
    is_double: false,
    is_featured: true,
    is_executive: false,
    is_suite: true,
  },
  {
    title: "Deluxe Twin Room",
    short_desc: "Twin beds with garden view — great for colleagues.",
    description:
      "The Deluxe Twin Room offers two single beds with premium mattresses, abundant natural light, and access to the garden terrace. A top pick for colleagues or friends.",
    price: 110,
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800",
    bed_count: 2,
    max_person: 2,
    floor: 4,
    room_size: 32,
    room_services: [],
    room_features: [],
    room_bathroom_features: [],
    room_rating: "4.4",
    is_active: true,
    sort_order: 8,
    is_booked: false,
    is_deluxe: true,
    is_double: true,
    is_featured: false,
    is_executive: false,
    is_suite: false,
  },
  {
    title: "Junior Suite",
    short_desc: "Mid-tier suite blending space with sophistication.",
    description:
      "Step up to our Junior Suite — a beautifully decorated space with a king bed, lounge corner, 55-inch smart TV, and premium bathroom with soaking tub.",
    price: 200,
    image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800",
    bed_count: 1,
    max_person: 2,
    floor: 6,
    room_size: 50,
    room_services: [],
    room_features: [],
    room_bathroom_features: [],
    room_rating: "4.7",
    is_active: true,
    sort_order: 9,
    is_booked: false,
    is_deluxe: false,
    is_double: false,
    is_featured: false,
    is_executive: false,
    is_suite: true,
  },
  {
    title: "Accessible Room",
    short_desc: "Thoughtfully designed for guests with mobility needs.",
    description:
      "Our Accessible Room is fully equipped for guests requiring mobility assistance — wide doorways, roll-in shower, lowered fixtures, and proximity to the elevator.",
    price: 85,
    image: "https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=800",
    bed_count: 1,
    max_person: 2,
    floor: 1,
    room_size: 38,
    room_services: [],
    room_features: [],
    room_bathroom_features: [],
    room_rating: "4.5",
    is_active: true,
    sort_order: 10,
    is_booked: false,
    is_deluxe: false,
    is_double: false,
    is_featured: false,
    is_executive: false,
    is_suite: false,
  },
];

// ─── DIVISIONS ───────────────────────────────────────────────────────────────
export const divisionsData = [
  {
    name: "Dhaka",
    slug: "dhaka",
    desc: "The capital and largest city of Bangladesh, a vibrant metropolis blending history, culture, and modernity.",
    thumbnail:
      "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800",
  },
  {
    name: "Chittagong",
    slug: "chittagong",
    desc: "Bangladesh's major seaport city, gateway to Cox's Bazar and the Chittagong Hill Tracts.",
    thumbnail:
      "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800",
  },
  {
    name: "Sylhet",
    slug: "sylhet",
    desc: "A picturesque division renowned for its sprawling tea gardens, wetlands, and the shrine of Hazrat Shah Jalal.",
    thumbnail:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
  },
  {
    name: "Rajshahi",
    slug: "rajshahi",
    desc: "Known as the Silk City, famous for its mangoes, lychees, and ancient archaeological sites.",
    thumbnail:
      "https://images.unsplash.com/photo-1541197250-0fca9fe8ae10?w=800",
  },
  {
    name: "Khulna",
    slug: "khulna",
    desc: "Home to the Sundarbans — the world's largest mangrove forest and habitat of the Royal Bengal Tiger.",
    thumbnail:
      "https://images.unsplash.com/photo-1509233725247-49e657c54213?w=800",
  },
  {
    name: "Barisal",
    slug: "barisal",
    desc: "The Venice of Bengal, celebrated for its waterways, floating markets, and scenic river cruises.",
    thumbnail:
      "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800",
  },
  {
    name: "Rangpur",
    slug: "rangpur",
    desc: "Northwestern agricultural heartland known for tobacco cultivation, historic monuments, and the Teesta River.",
    thumbnail:
      "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800",
  },
  {
    name: "Mymensingh",
    slug: "mymensingh",
    desc: "A culturally rich division featuring the Bangladesh Agricultural University, Brahmaputra River, and vibrant folk traditions.",
    thumbnail:
      "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800",
  },
  {
    name: "Cox's Bazar",
    slug: "coxs-bazar",
    desc: "Home to the world's longest unbroken natural sea beach, a premier tourist destination of Bangladesh.",
    thumbnail:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
  },
  {
    name: "Bandarban",
    slug: "bandarban",
    desc: "A breathtaking hill district featuring Boga Lake, Keokradong peak, and the indigenous Marma, Murong and Bawm communities.",
    thumbnail:
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
  },
];

// ─── FOOD ITEMS ───────────────────────────────────────────────────────────────
export const foodItemsData = [
  {
    title: "Beef Kacchi Biryani",
    desc: "Slow-cooked tender beef layered with fragrant basmati rice, saffron, and traditional spices.",
    price: 320,
    quantity: 50,
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800",
    is_active: true,
    sort_order: 1,
  },
  {
    title: "Chicken Roast",
    desc: "Whole roasted chicken marinated in yogurt and spices, served with naan and raita.",
    price: 280,
    quantity: 30,
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c7?w=800",
    is_active: true,
    sort_order: 2,
  },
  {
    title: "Hilsha Fish Curry",
    desc: "Classic Bengali mustard hilsha — the national dish of Bangladesh, simmered in rich mustard gravy.",
    price: 450,
    quantity: 20,
    image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800",
    is_active: true,
    sort_order: 3,
  },
  {
    title: "Shrimp Malai Curry",
    desc: "Jumbo prawns cooked in a creamy coconut and cashew sauce — a coastal Bengali delicacy.",
    price: 380,
    quantity: 25,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800",
    is_active: true,
    sort_order: 4,
  },
  {
    title: "Vegetable Khichuri",
    desc: "Comforting Bengali khichuri with mixed vegetables, lentils, and aromatic ghee — best on rainy days.",
    price: 150,
    quantity: 60,
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800",
    is_active: true,
    sort_order: 5,
  },
  {
    title: "Continental Breakfast Platter",
    desc: "Croissants, scrambled eggs, smoked salmon, fresh fruit, assorted jams, and freshly brewed coffee.",
    price: 420,
    quantity: 40,
    image: "https://images.unsplash.com/photo-1533920379810-6bedac961555?w=800",
    is_active: true,
    sort_order: 6,
  },
  {
    title: "Club Sandwich",
    desc: "Triple-decker toasted sandwich with chicken, bacon, lettuce, tomato, and creamy mayo.",
    price: 220,
    quantity: 45,
    image: "https://images.unsplash.com/photo-1567234669003-dce7a7a88821?w=800",
    is_active: true,
    sort_order: 7,
  },
  {
    title: "Cheese Margherita Pizza",
    desc: "Classic Neapolitan pizza with San Marzano tomato sauce, fresh mozzarella, and basil.",
    price: 350,
    quantity: 35,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800",
    is_active: true,
    sort_order: 8,
  },
  {
    title: "Grilled Salmon Fillet",
    desc: "Atlantic salmon fillet grilled to perfection, served with asparagus, lemon butter sauce, and pilaf.",
    price: 580,
    quantity: 15,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800",
    is_active: true,
    sort_order: 9,
  },
  {
    title: "Mango Lassi",
    desc: "Chilled blended yogurt drink with Rajshahi alphonso mango pulp, honey, and a hint of cardamom.",
    price: 120,
    quantity: 80,
    image: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800",
    is_active: true,
    sort_order: 10,
  },
  {
    title: "Chocolate Lava Cake",
    desc: "Warm dark chocolate fondant with a molten center, served with Madagascar vanilla bean ice cream.",
    price: 250,
    quantity: 30,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800",
    is_active: true,
    sort_order: 11,
  },
];

// ─── BLOGS ───────────────────────────────────────────────────────────────────
// Tags ObjectIds below should be replaced with real inserted IDs.
export const blogsData = [
  {
    title: "Top 10 Things to Do in Cox's Bazar",
    short_desc:
      "Discover the best activities and hidden gems along the world's longest natural sea beach.",
    content: `<p>Cox's Bazar stretches over 120 kilometres of uninterrupted sandy coastline, making it a bucket-list destination for travellers worldwide. Whether you're chasing waves, seeking serenity, or exploring local culture, this coastal paradise has it all.</p><p>Start your journey at Laboni Beach at sunrise — the golden hues reflecting on the Bay of Bengal are simply magical. From there, head north to Himchari National Park where a short hike rewards you with a dramatic hilltop waterfall and jungle panoramas.</p><p>Don't miss the colourful fishing village of Ramu, famous for its Buddhist temples and friendly locals. In the evening, sample freshly grilled seafood at the beachside stalls while watching the sun melt into the ocean.</p>`,
    slug: "top-10-things-to-do-in-coxs-bazar",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    gallery:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    category: "Travel Guide",
    tags: [],
    author: "Admin User",
    is_active: true,
    is_featured: true,
    is_local_activities: true,
    published_at: new Date("2025-01-15"),
    meta: "Cox's Bazar travel guide, things to do Cox's Bazar, Bangladesh beach",
    sort_order: 1,
  },
  {
    title: "Exploring the Sundarbans: A Complete Guide",
    short_desc:
      "Navigate the world's largest mangrove forest and spot the elusive Royal Bengal Tiger.",
    content: `<p>The Sundarbans is a UNESCO World Heritage Site shared between Bangladesh and India, covering nearly 10,000 square kilometres of tidal wetlands, mangrove forests, and serpentine waterways.</p><p>A guided boat tour through the labyrinthine creeks offers the chance to spot spotted deer, estuarine crocodiles, Irrawaddy dolphins, and if you're lucky — a Royal Bengal Tiger. Early morning and dusk are the best times for wildlife sightings.</p><p>The experience is as humbling as it is thrilling: deep in the forest, the only sounds are birdsong and water lapping against the mangrove roots. Stay overnight at a forest rest house for a truly immersive adventure.</p>`,
    slug: "exploring-the-sundarbans-complete-guide",
    image: "https://images.unsplash.com/photo-1509233725247-49e657c54213?w=800",
    gallery:
      "https://images.unsplash.com/photo-1509233725247-49e657c54213?w=800",
    category: "Adventure",
    tags: [],
    author: "Admin User",
    is_active: true,
    is_featured: true,
    is_local_activities: false,
    published_at: new Date("2025-02-10"),
    meta: "Sundarbans travel guide, Royal Bengal Tiger, mangrove forest Bangladesh",
    sort_order: 2,
  },
  {
    title: "A Food Lover's Guide to Bangladeshi Cuisine",
    short_desc:
      "From kacchi biryani to hilsha fish — a deep dive into the flavours of Bangladesh.",
    content: `<p>Bangladeshi cuisine is a symphony of spice, freshness, and comfort. Rooted in centuries of Mughal influence and riverine geography, it offers some of South Asia's most distinctive flavours.</p><p>The undisputed king is Hilsha (Ilish) — the national fish — best enjoyed as a mustard curry or smoked in banana leaf. Paired with steamed rice, it's the definitive Bengali meal.</p><p>For festive occasions, nothing beats Kacchi Biryani: layers of marinated beef and fragrant basmati slow-cooked in a sealed pot over charcoal. In Dhaka, Old Town's Haji Biriyani has been perfecting this art since 1939.</p>`,
    slug: "food-lovers-guide-bangladeshi-cuisine",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800",
    gallery:
      "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800",
    category: "Food & Culture",
    tags: [],
    author: "Admin User",
    is_active: true,
    is_featured: false,
    is_local_activities: false,
    published_at: new Date("2025-03-05"),
    meta: "Bangladeshi food guide, hilsha fish, kacchi biryani, Bengali cuisine",
    sort_order: 3,
  },
  {
    title: "Bandarban Hill Tracts: Trekking Through the Clouds",
    short_desc:
      "A guide to trekking Bangladesh's highest peaks and discovering indigenous cultures.",
    content: `<p>Bandarban district sits in the southeastern corner of Bangladesh where the land buckles upward into forested ridges that often sit above the clouds. Keokradong, at 1,230 metres, is the highest peak most trekkers aim for.</p><p>The trails wind through villages of the Marma, Murong, and Bawm communities — each with distinct textiles, languages, and traditions. A stay in an indigenous home-stay offers an authentic cultural exchange and hearty meals of bamboo-shoot curry and sticky rice.</p><p>Boga Lake, a mysterious glacial lake ringed by jungle-clad hills, is another highlight. Its deep emerald water and eerie stillness make it one of the most photogenic spots in the country.</p>`,
    slug: "bandarban-trekking-guide",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    gallery:
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    category: "Adventure",
    tags: [],
    author: "Admin User",
    is_active: true,
    is_featured: true,
    is_local_activities: true,
    published_at: new Date("2025-03-20"),
    meta: "Bandarban trekking, Keokradong, Boga Lake, Bangladesh hill tracts",
    sort_order: 4,
  },
  {
    title: "5 Reasons to Visit Sylhet's Tea Gardens",
    short_desc:
      "Roll through endless emerald tea estates and discover the spiritual heritage of Sylhet.",
    content: `<p>Sylhet division is a land of mist-laden hills carpeted in vivid green tea bushes. The region produces some of the finest orthodox teas in the world and its landscapes feel borrowed from a painting.</p><p>Srimangal — dubbed the 'Tea Capital of Bangladesh' — is ground zero for tea tourism. Visit the Lawachara National Park for birdwatching, then sample the famous seven-layer tea at Nilkantha Tea Cabin, a local legend.</p><p>The region is also home to the Hakaluki Haor, one of the largest freshwater wetlands in Asia — a migratory bird paradise. And the revered shrine of Hazrat Shah Jalal in Sylhet city draws hundreds of thousands of pilgrims year-round.</p>`,
    slug: "5-reasons-visit-sylhet-tea-gardens",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    gallery: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    category: "Travel Guide",
    tags: [],
    author: "Admin User",
    is_active: true,
    is_featured: false,
    is_local_activities: true,
    published_at: new Date("2025-04-01"),
    meta: "Sylhet tea gardens, Srimangal travel, seven layer tea Bangladesh",
    sort_order: 5,
  },
  {
    title: "A Weekend in Old Dhaka: History, Food & Chaos",
    short_desc:
      "Wander rickshaw-filled lanes, taste street food, and uncover centuries of Mughal heritage.",
    content: `<p>Old Dhaka is a sensory overload in the best possible way. A grid of narrow lanes packed with rickshaws, spice vendors, fabric traders, and street food stalls that have barely changed in centuries.</p><p>Begin at Lalbagh Fort — a 17th-century Mughal fort complex that tells the story of the city's founding. A short walk brings you to the Ahsan Manzil Pink Palace, a stunning Indo-Saracenic landmark on the Buriganga River.</p><p>By midday, head to Haji Biriyani or Nanna Biriyani for arguably Bangladesh's finest biryani. The evening calls for a river cruise on the Buriganga — watching the city skyline glow as the sun sets is an unforgettable experience.</p>`,
    slug: "weekend-old-dhaka-history-food-chaos",
    image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800",
    gallery:
      "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800",
    category: "City Guide",
    tags: [],
    author: "Admin User",
    is_active: true,
    is_featured: false,
    is_local_activities: false,
    published_at: new Date("2025-04-18"),
    meta: "Old Dhaka travel guide, Lalbagh Fort, Ahsan Manzil, Dhaka street food",
    sort_order: 6,
  },
  {
    title: "River Cruising in Barisal: The Venice of Bengal",
    short_desc:
      "Drift along the waterways of southern Bangladesh and discover floating markets and river life.",
    content: `<p>Barisal sits at the heart of Bangladesh's southern delta, where rivers outnumber roads and life revolves around the water. A river cruise here is not a tourist activity — it's the only way to move.</p><p>The most famous journey is the overnight Dhaka–Barisal rocket steamer, a beautifully preserved paddle steamer that has plied these routes since the British era. Booking a first-class cabin and watching the river world drift by at night is a quintessential Bangladesh experience.</p><p>By day, explore the Perojpur floating guava market — thousands of boats laden with fruit converge at dawn in a scene straight out of another century. The silence, the mist, and the colour are extraordinary.</p>`,
    slug: "river-cruising-barisal-venice-of-bengal",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800",
    gallery:
      "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800",
    category: "Travel Guide",
    tags: [],
    author: "Admin User",
    is_active: true,
    is_featured: false,
    is_local_activities: true,
    published_at: new Date("2025-05-02"),
    meta: "Barisal travel, rocket steamer Bangladesh, floating market Perojpur",
    sort_order: 7,
  },
  {
    title: "How to Plan the Perfect Hotel Stay in Bangladesh",
    short_desc:
      "Expert tips on choosing the right room, booking smart, and making the most of your stay.",
    content: `<p>Planning a hotel stay in Bangladesh doesn't need to be complicated, but a little preparation goes a long way — especially during peak seasons like Eid, winter (November–February), and the monsoon travel window.</p><p>When selecting a room, consider the floor level and view. Rooms above the 5th floor typically offer less street noise and better vistas. If you're a light sleeper, request rooms away from the elevator and ice machine areas.</p><p>Always ask about inclusions: many mid-to-upscale properties in Dhaka include airport transfers, breakfast, and complimentary laundry for multi-night stays if you ask during booking. Loyalty matters — repeat guests are frequently upgraded.</p>`,
    slug: "how-to-plan-perfect-hotel-stay-bangladesh",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
    gallery:
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
    category: "Travel Tips",
    tags: [],
    author: "Admin User",
    is_active: true,
    is_featured: false,
    is_local_activities: false,
    published_at: new Date("2025-05-20"),
    meta: "hotel booking Bangladesh tips, how to choose hotel room, travel Bangladesh",
    sort_order: 8,
  },
  {
    title: "Rajshahi Mango Season: A Fruity Pilgrimage",
    short_desc:
      "Every summer, mango lovers descend on Rajshahi for the sweetest fruit in the subcontinent.",
    content: `<p>From May to July, the orchards of Rajshahi and Chapainawabganj transform into a golden wonderland of over 300 mango varieties. The Langra, Fazli, Khirsapat (Himsagar), and Amrapali varieties are the crown jewels.</p><p>The best way to experience mango season is to rent a bicycle and ride through the Chapainawabganj orchards at dawn, when labourers are collecting the night's fallen fruit and the air smells impossibly sweet.</p><p>The region also produces the country's finest silk sarees — a Rajshahi Silk is a must-buy souvenir. Round off your visit at the Varendra Research Museum, Bangladesh's oldest museum, housing rare Hindu and Buddhist sculptures.</p>`,
    slug: "rajshahi-mango-season-fruity-pilgrimage",
    image: "https://images.unsplash.com/photo-1541197250-0fca9fe8ae10?w=800",
    gallery: "https://images.unsplash.com/photo-1541197250-0fca9fe8ae10?w=800",
    category: "Seasonal Guide",
    tags: [],
    author: "Admin User",
    is_active: true,
    is_featured: false,
    is_local_activities: true,
    published_at: new Date("2025-06-01"),
    meta: "Rajshahi mango season, Bangladesh mango tour, Chapainawabganj orchards",
    sort_order: 9,
  },
  {
    title: "Wellness & Spa: How to Recharge During Your Hotel Stay",
    short_desc:
      "From hot stone massage to yoga at dawn — the ultimate guide to hotel wellness in Bangladesh.",
    content: `<p>More travellers are now prioritising wellness when booking accommodation, and Bangladesh's premium hotels are rising to the occasion with world-class spa facilities, rooftop yoga sessions, and holistic wellness menus.</p><p>Start your morning with a guided sunrise yoga session on the hotel rooftop — the gentle stretches combined with views of the city awakening is a meditative way to begin the day. Follow with a steam session and a Moroccan hammam scrub at the spa.</p><p>Ayurvedic treatments using locally sourced herbs and oils are gaining popularity — treatments like the Shirodhara (warm oil head pour) or a four-hand synchronised massage are deeply restorative experiences. Book at least 48 hours in advance during peak season.</p>`,
    slug: "wellness-spa-hotel-stay-bangladesh",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800",
    gallery: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800",
    category: "Wellness",
    tags: [],
    author: "Admin User",
    is_active: true,
    is_featured: true,
    is_local_activities: false,
    published_at: new Date("2025-06-15"),
    meta: "hotel spa Bangladesh, wellness travel, Ayurvedic massage Dhaka",
    sort_order: 10,
  },
];
